### ISSUE TITLE
We should be explicit about how ClusterDeployments can extend the base ClusterTemplate

### ISSUE THREAD

**Issue by randybias** [k0rdent/docs#386]
The docs mostly have examples of using the base ClusterTemplate, which inherits certain defaults:

```yaml
# Cluster parameters
controlPlaneNumber: 3 # @schema description: The number of the control-plane machines; minimum: 1; type: integer; required: true
workersNumber: 2 # @schema description: The number of the worker machines; minimum: 1; type: integer; required: true

clusterNetwork: # @schema description: The cluster network configuration; type: object
  pods: # @schema description: The network ranges from which Pod networks are allocated; type: object
    cidrBlocks: # @schema description: A list of CIDR blocks; type: array; item: string
      - "10.244.0.0/16"
  services: # @schema description: The network ranges from which service VIPs are allocated; type: object
    cidrBlocks: # @schema description: A list of CIDR blocks; type: array; item: string
      - "10.96.0.0/12"

clusterLabels: {} # @schema description: Labels to apply to the cluster; type: object; additionalProperties: true
clusterAnnotations: {} # @schema description: Annotations to apply to the cluster; type: object; additionalProperties: true
```

We should include in the ClusterTemplateSpec and ClusterDeploymentSpec these additional parameters and probably give some examples of how you would use them.  One example might be how to "update" a cluster and resize it to have more worker nodes.

Above YAML from defaults in AWS:

https://github.com/k0rdent/kcm/blob/main/templates/cluster/aws-standalone-cp/values.yaml#L7

Might need some vetting from k0rdent eng team on what the "right" docs are in case there is variance across providers.
